### PR TITLE
a cat with eyes

### PR DESCRIPTION
**Pull request by L1cardo**
image

### CODE REVIEW

**Comment by Pointvar** [comment]
😂

**Comment by shinyzhu** [comment]
😹

**Comment by yichengchen** [comment]
cc @Dreamacro

**Comment by Dreamacro** [comment]
The menu bar icon is too small to see the detail of the icon. Add eyes to the icon seems a little wired

**Comment by L1cardo** [comment]
@Dreamacro It is possible to see the eyes of the cat on menu bar, and it is not wired.
image

**Comment by Dreamacro** [comment]
@L1cardo ok, LGTM

**Comment by evindu** [comment]
退出控制台后，Docker上的图标无法隐藏，点击Docker上关闭图标直接退出程序并不会在后台继续运行

**Comment by L1cardo** [comment]
@yichengchen Sorry to bother, since you don’t plan to merge , I am closing the PR

**Comment by yichengchen** [comment]
> @yichengchen Sorry to bother, since you don’t plan to merge , I am closing the PR

Sorry I forget this. The filesize of the image seems enlarge a lot, Have you compress it?

**Comment by yichengchen** [comment]
Please reopen this pr since Dreamacro agreed the changed @L1cardo

**Comment by Dreamacro** [comment]
@yichengchen https://github.com/yichengchen/clashX/pull/237#issuecomment-583711530 ???

**Pull request closed without merging**
